### ISSUE TITLE
more gwas catalog evidences?

### ISSUE THREAD

**Issue by elipapa** [opentargets/json_schema#18]
we only take:
rsID, p-value,panel size

but a more expansive list could be:
rsID, allele freq, p-value, OR/effect size, chromosomal position, mapped/reported genes, traits, study reference

This info can also be obtained by following the gwas catalog link, but users have asked to be able to download this directly from Open Targets Platform or API.
cc @ckongEbi

**Comment by ckongEbi** [comment]
@ElaineMcA @iandunham 
This can be done through GWAS feed to extend the data in their submission. Something that 
@afaulconbridge & @MichaelaEBI can work with Olga on

**Comment by iandunham** [comment]
This may have been supeceded by the Genetics portal
