### ISSUE TITLE
define mandatory and optional fields in the schema

### ISSUE THREAD

**Issue by elipapa** [opentargets/json_schema#3]
the webapp can break in unexpected ways if it depends on fields which are not always there (eg. some fields are not there for every gene). 

The difference should be coded in the schema, so the @opentargets/frontend team can know what to rely on

**Comment by ckongEbi** [comment]
@ElaineMcA part of the refactoring process.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #35](https://github.com/opentargets/platform/issues/35) via [**ZenHub**](https://www.zenhub.com/)
