### ISSUE TITLE
Add  Neuro Behavior Ontology as a valid source of ontology terms

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/json_schema#5]
All the neuro behaviour ontology terms imported in HP should be accepted during the validation step.
For instance, http://purl.obolibrary.org/obo/NBO_0000244 is the IRI that represents 'pathological anxiety'

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #32](https://github.com/opentargets/platform/issues/32) via [**ZenHub**](https://www.zenhub.com/)
