### ISSUE TITLE
Json Schema issue

### ISSUE THREAD

**Issue by Maatary** [opentargets/json_schema#59]
Dear Support team,

I have been looking at the schema and the data more closely. I am quite confuse somehow with not being able to find, certain properties that exist in the instances data that i can't see defined in the schema. 

For instance this is the beginning of many of your evidence data: 

 
{"id": "ffff8119c16671250210cf5cc7ce1f88", "loci": {"16": {"gene_end": 57863053, "gene_begin": 57758217}},

 
Nowhere in the Json Schema I have been able to find the property "loci", or "gene_end" or "gene_begin" or "id". 

Those are the evidence dataset of feb 2018. 

Hence could you help and point me to where i can find the definition of those property, or let me know if the schema is actually incomplete and you have rather a hard coded schema in the platform ?

**Comment by ckongEbi** [comment]
@Maatary the json schema in this repo, correspond to the validated index for each datasource  `18.02_validated*` , i believe the `"loci": {"16": {"gene_end": 57863053, "gene_begin": 57758217}}` information is from the `gene-data` index ?
