### ISSUE TITLE
Fix schema 1.2.4

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/json_schema#6]
* evidence.variant2disease.provenance_type.database.version = force it to be a string and should be mandatory even if empty
* evidence.variant2disease.provenance_type.database.dbxref,version = force it to be a string and should be mandatory even if empty
* evidence.gene2variant.provenance_type.database.version = force it to be a string and should be mandatory even if empty
* evidence.gene2variant.provenance_type.database.dbxref,version = force it to be a string and should be mandatory even if empty

SourceID: gwascatalog should be gwas_catalog (Olga) 
Ensure in EvidenceValidation that it's of type gwas_catalog

SourceID for eva_somatic should be eva_somatic and not EVA. We don't allow overlapping sources acros data types.

Map genetic_literature to genetic_association for G2P and UniProt instead of creating another datatype. 
Everything related to genetic association should be the same.

provenance type database version in evidence should be a string.

if genetic_association:
evidence.gene2variant.resource_score.value: should have a value
can be a problem for resources without a gene2variant mapping. So we should force to have this even if not used. 
same for functional consequence

* Remove identifiers.org from genes and map to ensembl ids (future)
* Remove identifiers.org from OpenTargets specific terms and remove reference to CTTV
* Keep only IRI that make sense for EFO, HP, MP, GO, ECO, SO, NBO (etc.)

* Remove list for targets and diseases (so back to a triple).

**Comment by ckongEbi** [comment]
@ElaineMcA we are at 1.2.8 now, if the above still an issue, re-open please
